apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkup-deployment
  labels:
    app: checkup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkup
  template:
    metadata:
      labels:
        app: checkup
    spec:
      containers:
      - name: checkup 
        image: artgelka/hospitality_checkup:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: CHECKUP_SQL_CONNECTONSTRING
          valueFrom:
            secretKeyRef:
              name: secrets
              key: checkupConnectionString
---

apiVersion: v1
kind: Service
metadata:
  name: checkup-service
spec:
  type: ClusterIP  
  selector:
    app: checkup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
