version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
         - ACCEPT_EULA=Y
         - MSSQL_SA_PASSWORD=1Secure*Password1
    ports:
        - 1433:1433
    volumes:
      - database:/var/opt/mssql
  hospitality.examination.api:
    image: ${DOCKER_REGISTRY-}hospitalityexaminationapi
    build:
      context: .
      dockerfile: src/Hospitality.Examination.API/Dockerfile
    depends_on:
      - db

  hospitality.checkup.api:
    image: ${DOCKER_REGISTRY-}hospitalitycheckupapi
    build:
      context: .
      dockerfile: src/Hospitality.CheckUp.API/Dockerfile
    depends_on:
      - db

  hospitality.identity.api:
    image: ${DOCKER_REGISTRY-}hospitalityidentityapi
    build:
      context: .
      dockerfile: src/Hospitality.Identity.API/Dockerfile
    depends_on:
      - db

  hospitality.government.insurance.api:
    image: ${DOCKER_REGISTRY-}hospitalitygovernmentinsuranceapi
    build:
      context: .
      dockerfile: src/Hospitality.Government.Insurance.API/Dockerfile

  hospitality.patient.api:
    image: ${DOCKER_REGISTRY-}hospitalitypatientapi
    build:
      context: .
      dockerfile: src/Hospitality.Patient.API/Dockerfile
    depends_on:
      - db

  hospitality.web:
    image: ${DOCKER_REGISTRY-}hospitalityweb
    build:
      context: .
      dockerfile: src/Hospitality.Web/Dockerfile

  hospitality.gateway.api:
    image: ${DOCKER_REGISTRY-}hospitalitygatewayapi
    build:
      context: .
      dockerfile: src/Hospitality.Gateway.API/Dockerfile

volumes:
  database:    
 





