apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostedservice-deployment
  labels:
    app: hostedservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostedservice
  template:
    metadata:
      labels:
        app: hostedservice
    spec:
      containers:
      - name: hostedservice
        image: tomakovv/hospitality_hostedservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: HOSTED_RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: configuration
              key: rabbitmq-url

---

apiVersion: v1
kind: Service
metadata:
  name: hostedservice-service
spec:
  type: ClusterIP  
  selector:
    app: hostedservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
