apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  sql-pass: MVNlY3VyZSZQYXNzd29yZDE=
  examinationConnectionString: ClNlcnZlcj1tc3NxbC1zZXJ2aWNlO0RhdGFiYXNlPUhvc3BpdGFsaXR5LkV4YW1pbmF0aW9ucztVc2VyPXNhO1Bhc3N3b3JkPTFTZWN1cmUmUGFzc3dvcmQxO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZQ==
  patientConnectionString: U2VydmVyPW1zc3FsLXNlcnZpY2U7RGF0YWJhc2U9SG9zcGl0YWxpdHkuUGF0aWVudHM7VXNlcj1zYTtQYXNzd29yZD0xU2VjdXJlJlBhc3N3b3JkMTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPXRydWU=