// <auto-generated />
using Hospitality.Examination.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospitality.Examination.Persistance.Migrations
{
    [DbContext(typeof(ExaminationContext))]
    [Migration("20220923081049_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationTypeId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExaminationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 80000000L,
                            Name = "USG kolana"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 100000000L,
                            Name = "USG jamy brzusznej"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 70000000L,
                            Name = "RTG głowy"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 60000000L,
                            Name = "RTG celowane na ząb obrotnika"
                        },
                        new
                        {
                            Id = 5,
                            Duration = 60000000L,
                            Name = "RTG styczne czaszki"
                        },
                        new
                        {
                            Id = 6,
                            Duration = 60000000L,
                            Name = "Leczenie kanałowe zębów"
                        },
                        new
                        {
                            Id = 7,
                            Duration = 80000000L,
                            Name = "Badanie kału na pasożyty"
                        },
                        new
                        {
                            Id = 8,
                            Duration = 100000000L,
                            Name = "Cytologia płynna"
                        },
                        new
                        {
                            Id = 9,
                            Duration = 70000000L,
                            Name = "Echo serca"
                        },
                        new
                        {
                            Id = 10,
                            Duration = 60000000L,
                            Name = "Gastroskopia"
                        });
                });

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationInfo", b =>
                {
                    b.HasOne("Hospitality.Examination.Domain.Entities.ExaminationType", "Type")
                        .WithMany()
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
