// <auto-generated />
using Hospitality.Examination.API.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospitality.Examination.Persistance.Migrations
{
    [DbContext(typeof(ExaminationContext))]
    [Migration("20220921090449_update-examinations")]
    partial class updateexaminations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExaminationTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExaminationTypeId");

                    b.ToTable("Examinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Checking if your hearing is good",
                            ExaminationTypeId = 1,
                            PatientId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Checking the teeth",
                            ExaminationTypeId = 2,
                            PatientId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Examination of the musculoskeletal system",
                            ExaminationTypeId = 3,
                            PatientId = 3,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Renal function test",
                            ExaminationTypeId = 4,
                            PatientId = 4,
                            Status = 2
                        });
                });

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExaminationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = 80000000L,
                            Name = "laryngologist"
                        },
                        new
                        {
                            Id = 2,
                            Duration = 100000000L,
                            Name = "dentist"
                        },
                        new
                        {
                            Id = 3,
                            Duration = 70000000L,
                            Name = "orthopedist"
                        },
                        new
                        {
                            Id = 4,
                            Duration = 60000000L,
                            Name = "nephrologist"
                        });
                });

            modelBuilder.Entity("Hospitality.Examination.Domain.Entities.ExaminationInfo", b =>
                {
                    b.HasOne("Hospitality.Examination.Domain.Entities.ExaminationType", "Type")
                        .WithMany()
                        .HasForeignKey("ExaminationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
